In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data = pd.read_csv("originalDataset.csv")

In [3]:
data.head()

Scorecard       Team 1     Team 2       Winner     Margin        Ground  \
0   ODI # 1    Australia    England    Australia  5 wickets     Melbourne   
1   ODI # 2      England  Australia      England  6 wickets    Manchester   
2   ODI # 3      England  Australia    Australia  5 wickets        Lord's   
3   ODI # 4      England  Australia      England  2 wickets    Birmingham   
4   ODI # 5  New Zealand   Pakistan  New Zealand    22 runs  Christchurch   

     Match Date  
0   Jan 5, 1971  
1  Aug 24, 1972  
2  Aug 26, 1972  
3  Aug 28, 1972  
4  Feb 11, 1973

In [4]:
data.tail()

Scorecard        Team 1       Team 2        Winner     Margin  \
3927  ODI # 3928         India  New Zealand   New Zealand  6 wickets   
3928  ODI # 3929  South Africa   Bangladesh  South Africa   200 runs   
3929  ODI # 3930      Pakistan    Sri Lanka      Pakistan  9 wickets   
3930  ODI # 3931         India  New Zealand         India  6 wickets   
3931  ODI # 3932         India  New Zealand         India     6 runs   

           Ground    Match Date  
3927       Mumbai  Oct 22, 2017  
3928  East London  Oct 22, 2017  
3929      Sharjah  Oct 23, 2017  
3930         Pune  Oct 25, 2017  
3931       Kanpur  Oct 29, 2017

## Manipulating Data into desired Format

In [5]:
def conv(x):
    if x=='Australia':
     return 0
    if x=='England':
     return 1
    if x=='New Zealand':
     return 2
    if x=='Pakistan':
     return 3
    if x=='India':
     return 4
    if x=='Sri Lanka':
     return 5
    if x=='South Africa':
     return 6
    if x=='West Indies':
     return 7
    if x=='Zimbabwe':
     return 8
    if x=='Kenya':
     return 9
    if x=='U.A.E.':
     return 10
    if x=='Bangladesh':
     return 11
    if x=='Canada':
     return 12
    if x=='Netherlands':
     return 12
    if x=='ICC World XI':
     return 13
    if x=='Africa XI':
     return 14
    if x=='Asia XI':
     return 15
    if x=='Bermuda':
     return 16
    if x=='Ireland':
     return 17
    if x=='Scotland':
     return 18
    if x=='Afghanistan':
     return 19
    if x=='P.N.G.':
      return 20
    if x=='Hong Kong':
     return 21 
    else:
     return 22


In [6]:
data['teamA'] = data['Team 1'].apply(conv)

In [7]:
data.head()

Scorecard       Team 1     Team 2       Winner     Margin        Ground  \
0   ODI # 1    Australia    England    Australia  5 wickets     Melbourne   
1   ODI # 2      England  Australia      England  6 wickets    Manchester   
2   ODI # 3      England  Australia    Australia  5 wickets        Lord's   
3   ODI # 4      England  Australia      England  2 wickets    Birmingham   
4   ODI # 5  New Zealand   Pakistan  New Zealand    22 runs  Christchurch   

     Match Date  teamA  
0   Jan 5, 1971      0  
1  Aug 24, 1972      1  
2  Aug 26, 1972      1  
3  Aug 28, 1972      1  
4  Feb 11, 1973      2

In [8]:
data['teamB'] = data['Team 2'].apply(conv)

In [9]:
data.tail()

Scorecard        Team 1       Team 2        Winner     Margin  \
3927  ODI # 3928         India  New Zealand   New Zealand  6 wickets   
3928  ODI # 3929  South Africa   Bangladesh  South Africa   200 runs   
3929  ODI # 3930      Pakistan    Sri Lanka      Pakistan  9 wickets   
3930  ODI # 3931         India  New Zealand         India  6 wickets   
3931  ODI # 3932         India  New Zealand         India     6 runs   

           Ground    Match Date  teamA  teamB  
3927       Mumbai  Oct 22, 2017      4      2  
3928  East London  Oct 22, 2017      6     11  
3929      Sharjah  Oct 23, 2017      3      5  
3930         Pune  Oct 25, 2017      4      2  
3931       Kanpur  Oct 29, 2017      4      2

In [10]:
data['WinnerTeam'] = data['Winner'].apply(conv)
data.head()

Scorecard       Team 1     Team 2       Winner     Margin        Ground  \
0   ODI # 1    Australia    England    Australia  5 wickets     Melbourne   
1   ODI # 2      England  Australia      England  6 wickets    Manchester   
2   ODI # 3      England  Australia    Australia  5 wickets        Lord's   
3   ODI # 4      England  Australia      England  2 wickets    Birmingham   
4   ODI # 5  New Zealand   Pakistan  New Zealand    22 runs  Christchurch   

     Match Date  teamA  teamB  WinnerTeam  
0   Jan 5, 1971      0      1           0  
1  Aug 24, 1972      1      0           1  
2  Aug 26, 1972      1      0           0  
3  Aug 28, 1972      1      0           1  
4  Feb 11, 1973      2      3           2

In [11]:
print(data['Ground'])

0          Melbourne
1         Manchester
2             Lord's
3         Birmingham
4       Christchurch
            ...     
3927          Mumbai
3928     East London
3929         Sharjah
3930            Pune
3931          Kanpur
Name: Ground, Length: 3932, dtype: object


In [12]:
data.Ground.unique()

array(['Melbourne', 'Manchester', "Lord's", 'Birmingham', 'Christchurch',
       'Swansea', 'Leeds', 'The Oval', 'Dunedin', 'Nottingham',
       'Wellington', 'Adelaide', 'Auckland', 'Scarborough', 'Sialkot',
       'Albion', 'Sahiwal', 'Lahore', "St John's", 'Castries', 'Quetta',
       'Sydney', 'Brisbane', 'Karachi', 'Perth', 'Kingstown', 'Hamilton',
       'Ahmedabad', 'Jalandhar', 'Cuttack', 'Colombo (SSC)', 'Amritsar',
       'Delhi', 'Hyderabad (Sind)', 'Bengaluru', 'Gujranwala', 'Multan',
       'Port of Spain', 'Napier', "St George's", 'Colombo (PSS)',
       'Taunton', 'Leicester', 'Bristol', 'Worcester', 'Southampton',
       'Derby', 'Tunbridge Wells', 'Chelmsford', 'Hyderabad (Deccan)',
       'Jaipur', 'Srinagar', 'Vadodara', 'Indore', 'Jamshedpur',
       'Guwahati', 'Moratuwa', 'Sharjah', 'Kingston', 'New Delhi',
       'Thiruvananthapuram', 'Peshawar', 'Faisalabad', 'Pune', 'Hobart',
       'Nagpur', 'Chandigarh', 'Bridgetown', 'Rawalpindi', 'Launceston',
       'Kandy

In [13]:
dict = {'Melbourne' : 0, 'Manchester' : 1, "Lord's" :2, 'Birmingham' : 3, 'Christchurch' :4,
       'Swansea': 5, 'Leeds' :6, 'The Oval' : 7, 'Dunedin' :8, 'Nottingham' :9,
       'Wellington' :10, 'Adelaide' :11, 'Auckland' :12, 'Scarborough' :13, 'Sialkot' :14,
       'Albion' :15, 'Sahiwal' :16, 'Lahore' :17, "St John's" :18, 'Castries' :19, 'Quetta' :20,
       'Sydney' :21, 'Brisbane' :22, 'Karachi' :23, 'Perth' :24, 'Kingstown' :25, 'Hamilton' :26,
       'Ahmedabad' :27, 'Jalandhar' :28, 'Cuttack' :29, 'Colombo (SSC)' :30, 'Amritsar' :31,
       'Delhi' :32, 'Hyderabad (Sind)' :33, 'Bengaluru' :34, 'Gujranwala' :35, 'Multan' :35,
       'Port of Spain' :36, 'Napier' :37, "St George's" :38, 'Colombo (PSS)' :39,
       'Taunton' :40, 'Leicester' :41, 'Bristol' :42, 'Worcester' :43, 'Southampton' :44,
       'Derby' :45, 'Tunbridge Wells' :46, 'Chelmsford' :47, 'Hyderabad (Deccan)' :48,
       'Jaipur' :49, 'Srinagar' :50, 'Vadodara' :51, 'Indore' :52, 'Jamshedpur' :53,
       'Guwahati' :54, 'Moratuwa' :55, 'Sharjah' :56, 'Kingston' :57, 'New Delhi' :58,
       'Thiruvananthapuram' :59, 'Peshawar' :60, 'Faisalabad' :61, 'Pune' :62, 'Hobart' :63,
       'Nagpur' :64, 'Chandigarh' :65, 'Bridgetown' :66, 'Rawalpindi' :67, 'Launceston' :68,
       'Kandy' :69, 'Colombo (RPS)' :70, 'Rajkot' :71, 'Kanpur' :72, 'Mumbai' :73,
       'Devonport' :74, 'Kolkata' :75, 'Chennai' :76, 'Faridabad' :77, 'Gwalior' :78,
       'Georgetown' :79, 'Dhaka' :80, 'Chittagong' :81, 'Visakhapatnam' :82,
       'Mumbai (BS)' :83, 'Margao' :84, 'Lucknow' :85, 'Sargodha' :86, 'New Plymouth' :87,
       'Mackay' :88, 'Ballarat' :89, 'Canberra' :90, 'Berri' :91, 'Albury' :92, 'Harare' :93,
       'Bulawayo' :94, 'Cape Town' :95, 'Port Elizabeth' :96, 'Centurion' :97,
       'Johannesburg' :98, 'Bloemfontein' :99, 'Durban' :100, 'East London' :101, 'Patna' :102,
       'Mohali' :103, 'Singapore' :104, 'Toronto' :105, 'Nairobi (Gym)' :106,
       'Nairobi (Club)' :107, 'Nairobi (Aga)' :108, 'Paarl' :109, 'Benoni' :110, 'Kochi' :111,
       'Kimberley' :112, 'Sheikhupura' :113, 'Taupo' :114, 'Hove' :115, 'Canterbury' :116,
       'Northampton' :117, 'Cardiff' :118, 'Chester-le-Street' :119, 'Dublin' :120,
       'Edinburgh' :121, 'Amstelveen' :122, 'Galle' :123, 'Melbourne (Docklands)' :124,
       'Potchefstroom' :125, 'Jodhpur' :126, 'Dambulla' :127, 'Nairobi' :128, 'Gros Islet' :129,
       'Tangier' :130, 'Vijayawada' :131, 'Kwekwe' :132, 'Queenstown' :133,
       'Pietermaritzburg' :134, 'Cairns' :135, 'Darwin' :136, 'Bogra' :137, 'Khulna' :138,
       'Fatullah' :139, 'Abu Dhabi' :140, 'Basseterre' :141, 'Belfast' :142, 'Ayr' :143,
       'Kuala Lumpur' :144, 'Mombasa' :145, 'Nairobi (Jaff)' :146, 'Nairobi (Ruaraka)' :147,
       'North Sound' :148, 'Providence' :149, 'Glasgow' :150, 'Rotterdam' :151,
       'King City (NW)': 152, 'Aberdeen' :153, 'Dubai (DSC)':154, 'Roseau' :155, 'The Hague' :156,
       'Schiedam' :157, 'Hambantota' :158, 'Pallekele' :159, 'Whangarei' :160, 'Ranchi' :161,
       'Dharamsala' :162, 'ICCA Dubai' :163, 'Dublin (Malahide)' :164, 'Nelson' :165,
       'Lincoln' :166, 'Mount Maunganui' :167, 'Townsville' :168, 'Mong Kok' :169,
       'Greater Noida':170, 'Port Moresby' :171}

In [14]:
data.replace({"Ground":dict},inplace=True)


In [15]:
data.Winner.unique()

array(['Australia', 'England', 'New Zealand', 'no result', 'West Indies',
       'Pakistan', 'India', 'Sri Lanka', 'Zimbabwe', 'tied',
       'South Africa', 'Kenya', 'U.A.E.', 'Bangladesh', 'Canada',
       'Netherlands', 'ICC World XI', 'Africa XI', 'Asia XI', 'Bermuda',
       'Ireland', 'Scotland', 'Afghanistan', 'P.N.G.', 'Hong Kong'],
      dtype=object)

In [16]:
data.head()

Scorecard       Team 1     Team 2       Winner     Margin  Ground  \
0   ODI # 1    Australia    England    Australia  5 wickets       0   
1   ODI # 2      England  Australia      England  6 wickets       1   
2   ODI # 3      England  Australia    Australia  5 wickets       2   
3   ODI # 4      England  Australia      England  2 wickets       3   
4   ODI # 5  New Zealand   Pakistan  New Zealand    22 runs       4   

     Match Date  teamA  teamB  WinnerTeam  
0   Jan 5, 1971      0      1           0  
1  Aug 24, 1972      1      0           1  
2  Aug 26, 1972      1      0           0  
3  Aug 28, 1972      1      0           1  
4  Feb 11, 1973      2      3           2

In [17]:
data.drop(['Scorecard' , 'Team 1' , 'Team 2' , 'Winner' ,'Margin' ,'Match Date'] , axis=1,inplace=True)

In [18]:
data.head()

Ground  teamA  teamB  WinnerTeam
0       0      0      1           0
1       1      1      0           1
2       2      1      0           0
3       3      1      0           1
4       4      2      3           2

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3932 entries, 0 to 3931
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Ground      3932 non-null   int64
 1   teamA       3932 non-null   int64
 2   teamB       3932 non-null   int64
 3   WinnerTeam  3932 non-null   int64
dtypes: int64(4)
memory usage: 123.0 KB


In [20]:
data.describe()

Ground        teamA        teamB   WinnerTeam
count  3932.000000  3932.000000  3932.000000  3932.000000
mean     62.382248     4.770600     5.297050     5.254069
std      45.985560     4.345984     4.110625     5.276752
min       0.000000     0.000000     0.000000     0.000000
25%      21.000000     2.000000     3.000000     2.000000
50%      56.000000     4.000000     5.000000     4.000000
75%      96.000000     7.000000     7.000000     7.000000
max     171.000000    22.000000    22.000000    22.000000

In [21]:
from sklearn.model_selection import train_test_split
train_set , test_set =train_test_split(data,test_size=0.2,random_state=42)
print(f"Rows in train set: {len(train_set)}\nRows in test set: {len(test_set)}\n")
                                    

Rows in train set: 3145
Rows in test set: 787



In [22]:
data = train_set.copy()
data_label = train_set["WinnerTeam"].copy()
data = train_set.drop("WinnerTeam" , axis=1)

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3145 entries, 2638 to 3174
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ground  3145 non-null   int64
 1   teamA   3145 non-null   int64
 2   teamB   3145 non-null   int64
dtypes: int64(3)
memory usage: 98.3 KB


In [24]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="median")
imputer.fit(data)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='median', verbose=0)

In [25]:
imputer.statistics_

array([56.,  4.,  5.])

In [26]:
X = imputer.transform(data)

In [27]:
data_tr = pd.DataFrame(X , columns=data.columns)

In [28]:
data_tr.describe()

Ground        teamA        teamB
count  3145.000000  3145.000000  3145.000000
mean     62.800000     4.767568     5.291574
std      46.070885     4.321785     4.123708
min       0.000000     0.000000     0.000000
25%      21.000000     2.000000     3.000000
50%      56.000000     4.000000     5.000000
75%      96.000000     7.000000     7.000000
max     171.000000    22.000000    22.000000

## Creating PipeLine

In [29]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipeline= Pipeline([
    ('imputer',SimpleImputer(strategy="median")),
    
])

In [30]:
data_num_tr = my_pipeline.fit_transform(data)

## Selecting Desired Model

In [35]:
from sklearn import linear_model
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVR
from sklearn import preprocessing
from sklearn import ensemble
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import ExtraTreesClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score


In [51]:
model = GradientBoostingClassifier()
model.fit(data,data_label)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [52]:
some_data = data.iloc[:5]

In [53]:
some_label = data_label.iloc[:5]

In [54]:
prepared_data = my_pipeline.transform(some_data)

In [55]:
model.predict(prepared_data)

array([6, 3, 6, 2, 1])

In [50]:
list(some_label)

[6, 3, 6, 2, 1]

## Evaluting the model

In [56]:
from sklearn.metrics import mean_squared_error
data_prediction = model.predict(data_num_tr)
mse = mean_squared_error(data_label , data_prediction)
rmse = np.sqrt(mse)

In [57]:
rmse

4.214857512108421

## Cross-Validation

In [58]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model,data_num_tr,data_label,scoring="neg_mean_squared_error",cv=10)
rmse_scores = np.sqrt(-scores)

/home/mayank/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)


In [59]:
rmse_scores

array([4.40922554, 4.59018968, 4.71673818, 4.64211227, 4.6084808 ,
       4.67511368, 5.09370787, 4.51853931, 5.35105204, 4.5623773 ])

## Saving The Model

In [60]:
from joblib import dump,load
dump(model,'Dragon.joblib')


['Dragon.joblib']

## Testing The Model

In [61]:
X_test = test_set.drop("WinnerTeam",axis=1)
Y_test = test_set["WinnerTeam"].copy()
X_test_prepared = my_pipeline.transform(X_test)
final_predictions = model.predict(X_test_prepared)
final_mse = mean_squared_error(Y_test, final_predictions)
final_rmse = np.sqrt(final_mse)

In [62]:
final_rmse

4.488868060836548

In [63]:
prepared_data[0]

array([35.,  3.,  6.])