In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data = pd.read_csv("playerlatest (2).csv")

In [3]:
data.head()

Unnamed: 0  100s  4 Wickets in Inn  50s  Balls Faced  Balls_Average  \
0           0     0                 0    0           15          38.09   
1           1     3                11   23         6252          31.84   
2           2     0                 9    1            0          29.30   
3           3     0                 1    0          263          38.07   
4           4     0                 0    0          166          51.75   

   Bat_Average  Bowl_Strike_rate  Ducks  Economy_Rate  ...  Maidens  Matches  \
0         8.00             34.55      1          6.62  ...        1        9   
1        29.71             40.67     14          4.70  ...      106      265   
2        13.67             38.48     12          4.57  ...       70      153   
3         8.35             54.13      4          4.22  ...       12       31   
4        20.57             54.00      2          5.75  ...        2        9   

   Not Outs  Opening Batting   Overs  Runs  Runs_Conceded  Strike Rate  \
0         2                0    63.2     8          419.0        53.33   
1        57                3  1823.3  5080         8564.0        81.25   
2        40                0  1327.3   779         6065.0         0.00   
3         6                0   270.4   142         1142.0        53.99   
4         1                0    72.0   144          414.0        86.75   

   Wickets  performance  
0       11           65  
1      269           75  
2      207           81  
3       30           61  
4        8           42  

[5 rows x 21 columns]

In [4]:
d = pd.read_csv("playerlatest (2).csv" , index_col="Wickets")
first = d.loc[24]
print(first)

         Unnamed: 0  100s  4 Wickets in Inn  50s  Balls Faced  Balls_Average  \
Wickets                                                                        
24               54     0                 0    1          465          36.58   
24              242     0                 2    0          117          34.08   
24              385     0                 1    0          152          29.71   
24              458     0                 0    0          134          53.50   
24              728     1                 0    6         1605          41.17   
24              820     0                 0    0           91          40.83   
24              855     0                 1    1          517          45.46   
24              925     0                 0    1          113          26.75   
24              937     0                 0    0           52          49.21   
24             1505     0                 3    0          161          23.21   

         Bat_Average  Bowl_Strike_rate 

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Unnamed: 0        1599 non-null   int64  
 1   100s              1599 non-null   int64  
 2   4 Wickets in Inn  1599 non-null   int64  
 3   50s               1599 non-null   int64  
 4   Balls Faced       1599 non-null   int64  
 5   Balls_Average     1599 non-null   float64
 6   Bat_Average       1599 non-null   float64
 7   Bowl_Strike_rate  1599 non-null   float64
 8   Ducks             1599 non-null   int64  
 9   Economy_Rate      1599 non-null   float64
 10  Innings           1599 non-null   int64  
 11  Maidens           1599 non-null   int64  
 12  Matches           1599 non-null   int64  
 13  Not Outs          1599 non-null   int64  
 14  Opening Batting   1599 non-null   int64  
 15  Overs             1599 non-null   float64
 16  Runs              1599 non-null   int64  


In [6]:
data.describe()

Unnamed: 0         100s  4 Wickets in Inn          50s   Balls Faced  \
count  1599.000000  1599.000000       1599.000000  1599.000000   1599.000000   
mean    799.000000     0.883677          0.898061     3.978737    984.630394   
std     461.735855     3.346338          2.438785    10.713567   2210.348893   
min       0.000000     0.000000          0.000000     0.000000      0.000000   
25%     399.500000     0.000000          0.000000     0.000000     39.000000   
50%     799.000000     0.000000          0.000000     0.000000    175.000000   
75%    1198.500000     0.000000          1.000000     2.000000    752.500000   
max    1598.000000    49.000000         27.000000    96.000000  21367.000000   

       Balls_Average  Bat_Average  Bowl_Strike_rate        Ducks  \
count    1599.000000  1599.000000       1599.000000  1599.000000   
mean       25.459887    16.995184         29.923552     2.717323   
std        26.845620    13.179514         30.301800     4.194596   
min         0.000000     0.000000          0.000000     0.000000   
25%         0.000000     6.670000          0.000000     0.000000   
50%        27.140000    14.980000         32.670000     1.000000   
75%        38.080000    25.340000         46.360000     3.000000   
max       201.000000   120.500000        222.000000    34.000000   

       Economy_Rate  ...      Maidens      Matches     Not Outs  \
count   1599.000000  ...  1599.000000  1599.000000  1599.000000   
mean       3.922295  ...     9.063790    41.137586     6.041901   
std        2.846450  ...    23.809048    63.835529     9.993245   
min        0.000000  ...     0.000000     1.000000     0.000000   
25%        0.000000  ...     0.000000     4.000000     0.000000   
50%        4.710000  ...     1.000000    15.000000     2.000000   
75%        5.500000  ...     6.000000    49.000000     7.000000   
max       26.000000  ...   313.000000   463.000000    82.000000   

       Opening Batting        Overs          Runs  Runs_Conceded  Strike Rate  \
count      1599.000000  1599.000000   1599.000000    1599.000000  1599.000000   
mean          7.522201   164.840588    755.872420     782.416617    61.674797   
std          27.745344   345.932352   1770.334164    1579.958715    29.088485   
min           0.000000     0.000000      0.000000       0.000000     0.000000   
25%           0.000000     3.050000     20.000000       0.000000    47.170000   
50%           0.000000    26.300000    110.000000     129.000000    64.230000   
75%           2.000000   153.150000    559.000000     747.500000    79.305000   
max         383.000000  3135.100000  18426.000000   13632.000000   328.570000   

           Wickets  performance  
count  1599.000000  1599.000000  
mean     24.280801    50.435272  
std      54.091709    28.188586  
min       0.000000     0.000000  
25%       0.000000    24.000000  
50%       3.000000    57.000000  
75%      20.000000    73.000000  
max     534.000000    98.000000  

[8 rows x 21 columns]

In [7]:
from sklearn.model_selection import train_test_split
train_set , test_set = train_test_split(data,test_size=0.3,random_state=42)
print(f"Rows in train set: {len(train_set)}\nRows in test set: {len(test_set)}\n")
                                    

Rows in train set: 1119
Rows in test set: 480



In [8]:
data = train_set.copy()
data_label = train_set["performance"].copy()
data = train_set.drop("performance" , axis=1)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1119 entries, 925 to 1126
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Unnamed: 0        1119 non-null   int64  
 1   100s              1119 non-null   int64  
 2   4 Wickets in Inn  1119 non-null   int64  
 3   50s               1119 non-null   int64  
 4   Balls Faced       1119 non-null   int64  
 5   Balls_Average     1119 non-null   float64
 6   Bat_Average       1119 non-null   float64
 7   Bowl_Strike_rate  1119 non-null   float64
 8   Ducks             1119 non-null   int64  
 9   Economy_Rate      1119 non-null   float64
 10  Innings           1119 non-null   int64  
 11  Maidens           1119 non-null   int64  
 12  Matches           1119 non-null   int64  
 13  Not Outs          1119 non-null   int64  
 14  Opening Batting   1119 non-null   int64  
 15  Overs             1119 non-null   float64
 16  Runs              1119 non-null   int64 

In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="median")
imputer.fit(data)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='median', verbose=0)

In [11]:
imputer.statistics_

array([810.  ,   0.  ,   0.  ,   0.  , 169.  ,  27.61,  14.63,  33.07,
         1.  ,   4.74,  11.  ,   1.  ,  15.  ,   2.  ,   0.  ,  27.  ,
       108.  , 131.  ,  64.64,   3.  ])

In [12]:
X = imputer.transform(data)

In [13]:
data_tr = pd.DataFrame(X , columns=data.columns)

In [14]:
data_tr.describe()

Unnamed: 0         100s  4 Wickets in Inn          50s   Balls Faced  \
count  1119.000000  1119.000000       1119.000000  1119.000000   1119.000000   
mean    800.915103     0.855228          0.881144     3.787310    946.191242   
std     461.045942     3.212585          2.438362    10.330209   2136.280375   
min       0.000000     0.000000          0.000000     0.000000      0.000000   
25%     403.500000     0.000000          0.000000     0.000000     38.500000   
50%     810.000000     0.000000          0.000000     0.000000    169.000000   
75%    1188.000000     0.000000          1.000000     2.000000    738.500000   
max    1598.000000    49.000000         27.000000    96.000000  21367.000000   

       Balls_Average  Bat_Average  Bowl_Strike_rate        Ducks  \
count    1119.000000  1119.000000       1119.000000  1119.000000   
mean       25.628239    16.961868         30.045371     2.587131   
std        26.288936    13.516323         29.637551     4.010636   
min         0.000000     0.000000          0.000000     0.000000   
25%         0.000000     6.615000          0.000000     0.000000   
50%        27.610000    14.630000         33.070000     1.000000   
75%        38.525000    25.255000         46.450000     3.000000   
max       201.000000   120.500000        222.000000    34.000000   

       Economy_Rate      Innings      Maidens      Matches     Not Outs  \
count   1119.000000  1119.000000  1119.000000  1119.000000  1119.000000   
mean       3.985094    31.304736     8.654155    39.679178     5.840929   
std        2.775638    53.125843    22.144087    61.510720     9.872247   
min        0.000000     0.000000     0.000000     1.000000     0.000000   
25%        0.000000     3.000000     0.000000     4.000000     0.000000   
50%        4.740000    11.000000     1.000000    15.000000     2.000000   
75%        5.555000    36.000000     6.000000    49.000000     7.000000   
max       24.000000   452.000000   277.000000   463.000000    82.000000   

       Opening Batting        Overs          Runs  Runs_Conceded  Strike Rate  \
count      1119.000000  1119.000000   1119.000000    1119.000000  1119.000000   
mean          7.596068   159.965773    725.584450     762.772565    62.088195   
std          28.568022   336.220426   1706.044232    1540.976525    30.016583   
min           0.000000     0.000000      0.000000       0.000000     0.000000   
25%           0.000000     4.000000     20.000000       0.000000    47.795000   
50%           0.000000    27.000000    108.000000     131.000000    64.640000   
75%           2.000000   151.650000    572.000000     737.500000    79.565000   
max         383.000000  3135.100000  18426.000000   12326.000000   328.570000   

           Wickets  
count  1119.000000  
mean     23.529044  
std      52.671178  
min       0.000000  
25%       0.000000  
50%       3.000000  
75%      20.000000  
max     534.000000

## Creating Pipeline

In [15]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipeline = Pipeline([
    ('imputer',SimpleImputer(strategy="median")),
    
    
])

In [16]:
data_num_tr = my_pipeline.fit_transform(data)

## Selecting Desired Model

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
#model = LinearRegression()
#model = DecisionTreeRegressor()
model = RandomForestRegressor()
model.fit(data, data_label)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [18]:
some_data = data.iloc[:5]

In [19]:
some_label = data_label.iloc[:5]

In [20]:
prepared_data = my_pipeline.transform(some_data)

In [21]:
model.predict(prepared_data)

array([86.46, 49.06, 27.54, 61.82, 13.28])

In [22]:
list(some_label)

[87, 48, 24, 66, 10]

## Evaluating the model

In [23]:
from sklearn.metrics import mean_squared_error
data_prediction = model.predict(data_num_tr)
mse = mean_squared_error(data_label , data_prediction)
rmse = np.sqrt(mse)

In [24]:
rmse

3.0579322860311575

## Cross-Validation

In [25]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model,data_num_tr,data_label,scoring="neg_mean_squared_error",cv=10)
rmse_scores = np.sqrt(-scores)

In [26]:
rmse_scores

array([ 6.05213532,  5.44647666, 11.52673643,  6.13749949,  5.97964434,
        9.0982068 ,  4.97896109, 10.94121802, 13.28968837,  4.76613807])

def print_scores(scores):
    print("scores:",scores)
    print("Mean:",scores.mean())
    print("Standard Deviation:", scores.std())

In [27]:
print(rmse_scores)

[ 6.05213532  5.44647666 11.52673643  6.13749949  5.97964434  9.0982068
  4.97896109 10.94121802 13.28968837  4.76613807]


## Saving The Model

In [28]:
from joblib import dump,load
dump(model,'Dragon.joblib')

['Dragon.joblib']

## Testing The Model

In [29]:
X_test = test_set.drop("performance",axis=1)
Y_test = test_set["performance"].copy()
X_test_prepared = my_pipeline.transform(X_test)
final_predictions = model.predict(X_test_prepared)
final_mse = mean_squared_error(Y_test, final_predictions)
final_rmse = np.sqrt(final_mse)
##print(final_predictions , list(Y_test))

In [30]:
final_rmse

9.826278585168106

In [31]:
prepared_data[0]

array([925.  ,   0.  ,   0.  ,   1.  , 113.  ,  26.75,  16.83,  33.58,
         1.  ,   4.78,   7.  ,   5.  ,  16.  ,   1.  ,   0.  , 134.2 ,
       101.  , 642.  ,  89.38,  24.  ])